# DataSource Config
spring:
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql